cmake_minimum_required(VERSION 3.26.0)

set(TARGET_WINDOWS FALSE)
set(TARGET_LINUX FALSE)
set(TARGET_MACOS FALSE)

if(CMAKE_SYSTEM_NAME STREQUAL "Windows" OR (CMAKE_CROSSCOMPILING AND CMAKE_SYSTEM_NAME STREQUAL "Windows"))
    set(TARGET_WINDOWS TRUE)
    if(CMAKE_CROSSCOMPILING)
        message(STATUS "PlatformDetection: Cross-compile for Windows.")
    else()
        message(STATUS "PlatformDetection: Native compile for Windows.")
    endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(TARGET_LINUX TRUE)
    message(STATUS "PlatformDetection: Native compile for Linux.")
else()
    message(STATUS "PlatformDetection: System wasnt determined: ${CMAKE_SYSTEM_NAME}")
endif()

if (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
    message(STATUS "Building for x64")
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "x86|i386|i686")
    message(STATUS "Building for x86")
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "armv7")
    message(STATUS "Building for ARM32")
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
    message(STATUS "Building for ARM64")
else()
    message(STATUS "Unknown architecture: ${CMAKE_SYSTEM_PROCESSOR}")
endif()


if (CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(STATUS "Void pointer 64-bit")
else()
    message(STATUS "Void pointer 32-bit")
endif()

message(STATUS "Host CPU: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
message(STATUS "Target CPU: ${CMAKE_SYSTEM_PROCESSOR}")
