cmake_minimum_required(VERSION 3.26.0)

set(TARGET_WINDOWS FALSE)
set(TARGET_LINUX FALSE)
set(TARGET_MACOS FALSE)

if(CMAKE_SYSTEM_NAME STREQUAL "Windows" OR (CMAKE_CROSSCOMPILING AND CMAKE_SYSTEM_NAME STREQUAL "Windows"))
    set(TARGET_WINDOWS TRUE)
    if(CMAKE_CROSSCOMPILING)
        message(STATUS "PlatformDetection: Cross-compile for Windows.")
    else()
        message(STATUS "PlatformDetection: Native compile for Windows.")
    endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(TARGET_LINUX TRUE)
    message(STATUS "PlatformDetection: Native compile for Linux.")
else()
    message(STATUS "PlatformDetection: System wasnt determined: ${CMAKE_SYSTEM_NAME}")
endif()
